// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VaultInterface is an autogenerated mock type for the VaultInterface type
type VaultInterface struct {
	mock.Mock
}

// DeleteSecrets provides a mock function with given fields: secretid
func (_m *VaultInterface) DeleteSecrets(secretid string) error {
	ret := _m.Called(secretid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(secretid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSecrets provides a mock function with given fields: secretid
func (_m *VaultInterface) GetSecrets(secretid string) (map[string]interface{}, error) {
	ret := _m.Called(secretid)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(secretid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(secretid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSecrets provides a mock function with given fields: secretName, data
func (_m *VaultInterface) SetSecrets(secretName string, data map[string]interface{}) error {
	ret := _m.Called(secretName, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(secretName, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
