// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import (
	api "github.com/hashicorp/vault/api"

	mock "github.com/stretchr/testify/mock"
)

// VaultClientInterface is an autogenerated mock type for the VaultClientInterface type
type VaultClientInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: path
func (_m *VaultClientInterface) Delete(path string) (*api.Secret, error) {
	ret := _m.Called(path)

	var r0 *api.Secret
	if rf, ok := ret.Get(0).(func(string) *api.Secret); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: path
func (_m *VaultClientInterface) Get(path string) (*api.Secret, error) {
	ret := _m.Called(path)

	var r0 *api.Secret
	if rf, ok := ret.Get(0).(func(string) *api.Secret); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: path, data
func (_m *VaultClientInterface) Set(path string, data map[string]interface{}) (*api.Secret, error) {
	ret := _m.Called(path, data)

	var r0 *api.Secret
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) *api.Secret); ok {
		r0 = rf(path, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]interface{}) error); ok {
		r1 = rf(path, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
